# packages in environment at /bph/puredata1/bioinfdata/share/envs/deeplearning_gpu_nils:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    anaconda
_tflow_180_select         1.0                         gpu    anaconda
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.7.1                    py36_0    anaconda
astor                     0.7.1                    py36_0    anaconda
backcall                  0.1.0                    py36_0    anaconda
blas                      1.0                         mkl    anaconda
bleach                    1.5.0                    py36_0    https://repo.anaconda.com/pkgs/free
bzip2                     1.0.6                h14c3975_5    anaconda
c-ares                    1.15.0               h7b6447c_1    anaconda
ca-certificates           2020.6.24                     0  
cairo                     1.14.12              h8948797_3    anaconda
certifi                   2020.6.20                py36_0  
cudatoolkit               9.0                  h13b8566_0    anaconda
cudnn                     7.1.2                 cuda9.0_0    anaconda
cupti                     9.0.176                       0    anaconda
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.5                   pypi_0    pypi
dbus                      1.13.2               h714fa37_1    anaconda
decorator                 4.3.2                    py36_0    anaconda
entrypoints               0.3                      py36_0    anaconda
expat                     2.2.6                he6710b0_0    anaconda
ffmpeg                    4.0                  hcdf2ecd_0    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freeglut                  3.0.0                hf484d3e_5    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
gast                      0.2.2                    py36_0    anaconda
glib                      2.56.2               hd408876_0    anaconda
gmp                       6.1.2                h6c8ec71_1  
graphite2                 1.3.11               h16798f4_2    anaconda
grpcio                    1.12.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.8.0            py36h989c5e5_3    anaconda
harfbuzz                  1.8.8                hffaf4a1_0    anaconda
hdf5                      1.10.2               hba1933b_1    anaconda
html5lib                  0.9999999                py36_0    https://repo.anaconda.com/pkgs/free
icu                       58.2                 h9c2bf20_1  
imbalanced-learn          0.2.1                    py36_0    glemaitre
intel-openmp              2018.0.3                      0    anaconda
ipykernel                 5.1.0                    pypi_0    pypi
ipython                   6.4.0                    pypi_0    pypi
ipython_genutils          0.2.0                    py36_0    anaconda
ipywidgets                7.4.2                    pypi_0    pypi
jasper                    2.0.14               h07fcdf6_1    anaconda
jedi                      0.13.2                   py36_0    anaconda
jinja2                    2.10                     pypi_0    pypi
joblib                    0.13.2                   py36_0    anaconda
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.2.4                    pypi_0    pypi
jupyter-console           5.2.0                    pypi_0    pypi
jupyter-core              4.4.0                    pypi_0    pypi
keras                     2.2.4                         0    anaconda
keras-applications        1.0.8                      py_0    anaconda
keras-base                2.2.4                    py36_0    anaconda
keras-preprocessing       1.1.0                      py_1    anaconda
kiwisolver                1.0.1            py36h764f252_0  
libblas                   3.8.0           8_h8933c1f_netlib    conda-forge
libcblas                  3.8.0           8_h8933c1f_netlib    conda-forge
libedit                   3.1.20181209         hc058e9b_0    anaconda
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.2.0                hdf63c60_3    anaconda
libglu                    9.0.0                hf484d3e_1    anaconda
libopencv                 3.4.2                hb342d67_1    anaconda
libopus                   1.2.1                hb9ed12e_0  
libpng                    1.6.36               hbc83047_0    anaconda
libprotobuf               3.8.0                hd408876_0    anaconda
libsodium                 1.0.16               h1bed415_0    anaconda
libstdcxx-ng              8.2.0                hdf63c60_1    anaconda
libtiff                   4.0.9                he85c1e1_1    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libvpx                    1.7.0                h439df22_0    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.8                h26e45fe_1    anaconda
m2w64-gcc-libgfortran     5.3.0                         6    https://repo.anaconda.com/pkgs/msys2
m2w64-gcc-libs            5.3.0                         7    https://repo.anaconda.com/pkgs/msys2
m2w64-gcc-libs-core       5.3.0                         7    https://repo.anaconda.com/pkgs/msys2
m2w64-gmp                 6.1.0                         2    https://repo.anaconda.com/pkgs/msys2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    https://repo.anaconda.com/pkgs/msys2
markdown                  3.1.1                    py36_0    anaconda
markupsafe                1.1.0            py36h7b6447c_0    anaconda
matplotlib                2.2.3                    pypi_0    pypi
mistune                   0.8.4            py36h7b6447c_0    anaconda
mkl                       2018.0.3                      1    anaconda
mkl_fft                   1.0.6            py36h7dd41cf_0    anaconda
mkl_random                1.0.1            py36h4414c95_1    anaconda
mock                      3.0.5                    py36_0    anaconda
msys2-conda-epoch         20160418                      1    https://repo.anaconda.com/pkgs/msys2
nbconvert                 5.3.1                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1    anaconda
notebook                  5.7.4                    pypi_0    pypi
numpy                     1.15.4           py36h1d66e8a_0    anaconda
numpy-base                1.15.4           py36h81de0dd_0    anaconda
opencv                    3.4.2            py36h6fd60c2_1    anaconda
openssl                   1.1.1g               h7b6447c_0  
pandas                    0.25.0                   pypi_0    pypi
pandoc                    2.2.3.2                       0    anaconda
pandocfilters             1.4.2                    py36_1    anaconda
parso                     0.3.2                    py36_0    anaconda
pcre                      8.42                 h439df22_0    anaconda
pexpect                   4.6.0                    py36_0    anaconda
pickleshare               0.7.5                    py36_0    anaconda
pillow                    5.2.0                    pypi_0    pypi
pip                       18.0                     pypi_0    pypi
pixman                    0.34.0               hceecf20_3  
prometheus_client         0.5.0                    py36_0    anaconda
prompt-toolkit            1.0.15                   pypi_0    pypi
protobuf                  3.8.0            py36he6710b0_0    anaconda
ptyprocess                0.6.0                    py36_0    anaconda
py-opencv                 3.4.2            py36hb342d67_1    anaconda
pygments                  2.2.0                    pypi_0    pypi
pyparsing                 2.2.0            py36hee85983_1    anaconda
pyqt                      5.9.2            py36h751905a_0    anaconda
python                    3.6.8                h0371630_0    anaconda
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.6                     0_cp36m    conda-forge
pytz                      2018.4                   py36_0    anaconda
pyyaml                    5.1.1            py36h7b6447c_0    anaconda
pyzmq                     17.1.2           py36he6710b0_2    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.4.3                    pypi_0    pypi
readline                  7.0                  h7b6447c_5    anaconda
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0            py36hfa4b5c9_1    anaconda
send2trash                1.5.0                    py36_0    anaconda
setuptools                41.0.1                   py36_0    anaconda
simplegeneric             0.8.1                    py36_2    anaconda
sip                       4.19.8           py36hf484d3e_0    anaconda
six                       1.12.0                   py36_0    anaconda
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.28.0               h7b6447c_0    anaconda
tensorboard               1.13.1           py36hf484d3e_0    anaconda
tensorflow                1.5.0                         0    anaconda
tensorflow-base           1.5.0            py36hff88cb2_1    anaconda
tensorflow-estimator      1.13.0                     py_0    anaconda
tensorflow-gpu            1.5.0                         0    anaconda
tensorflow-gpu-base       1.5.0            py36h8a131e3_0    anaconda
tensorflow-tensorboard    1.5.1            py36hf484d3e_1    anaconda
termcolor                 1.1.0                    py36_1    anaconda
terminado                 0.8.1                    py36_1    anaconda
testpath                  0.4.2                    py36_0    anaconda
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  0.15.1                   pypi_0    pypi
tk                        8.6.8                hbc83047_0    anaconda
tornado                   5.0.2                    py36_0    anaconda
tqdm                      4.31.1                     py_0    anaconda
traitlets                 4.3.2                    pypi_0    pypi
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.1.7                    py36_0    anaconda
werkzeug                  0.15.4                     py_0    anaconda
wheel                     0.33.4                   py36_0    anaconda
widgetsnbextension        3.4.2                    pypi_0    pypi
xz                        5.2.4                h14c3975_4    anaconda
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
